[tool.poetry]
name = "torrent2emby"
version = "0.1.0"
description = "Проект для сккачивания и управления фильмами и сериалами"
authors = ["kiling <kiling@bk.ru>"]
packages = [{include = "src"}]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8"
requests = "^2.32.3"

[tool.poetry.scripts]
api = "src.server.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
